openapi: 3.0.3
info:
  title: Movie Graph API
  description: API for querying movie and person relationships in a graph database
  version: 1.0.0
servers:
  - url: /api/v1
    description: Version 1 of the Movie Graph API

components:
  schemas:
    Vertex:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier (tconst for movies, nconst for people)
        label:
          type: string
          enum: [movie, person]
          description: Type of vertex
    
    Edge:
      type: object
      properties:
        id:
          type: string
          description: Edge identifier
        from:
          type: string
          description: Source vertex ID
        to:
          type: string
          description: Target vertex ID
        label:
          type: string
          enum: [appears_in]
          description: Type of relationship
    
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code for client handling

paths:
  /vertices/{id}:
    get:
      summary: Get vertex by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The vertex identifier
      responses:
        '200':
          description: Vertex retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vertex'
        '404':
          description: Vertex not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /vertices/{id}/edges:
    get:
      summary: Get edges connected to a vertex
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The vertex identifier
        - name: direction
          in: query
          required: false
          schema:
            type: string
            enum: [in, out, both]
            default: both
          description: Direction of edges to retrieve
      responses:
        '200':
          description: Connected edges retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Edge'

  /vertices/{id}/neighbors:
    get:
      summary: Get neighboring vertices
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: The vertex identifier
        - name: direction
          in: query
          required: false
          schema:
            type: string
            enum: [in, out, both]
            default: both
          description: Direction of traversal
        - name: label
          in: query
          required: false
          schema:
            type: string
            enum: [movie, person]
          description: Filter neighbors by vertex label
      responses:
        '200':
          description: Neighboring vertices retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vertex'

  /search:
    get:
      summary: Search vertices
      parameters:
        - name: label
          in: query
          required: true
          schema:
            type: string
            enum: [movie, person]
          description: Type of vertices to search for
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 10
            maximum: 100
          description: Maximum number of results to return
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
          description: Number of results to skip for pagination
      responses:
        '200':
          description: Search results retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                    description: Total number of results
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Vertex' 